//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InmobiliariaForms.InmobiliariaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarVendedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesParaInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarInmueblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVendedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInteresadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFotosDelInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarFotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestNotificarSobreInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificarSobreInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestNotificarSobreInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificarSobreInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarVendedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDolarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDolarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubirInmuebleWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback Test2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Test3OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::InmobiliariaForms.Properties.Settings.Default.Sistema_Integral_Inmobiliario_InmobiliariaService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event GuardarInmuebleCompletedEventHandler GuardarInmuebleCompleted;
        
        /// <remarks/>
        public event GuardarInteresadoCompletedEventHandler GuardarInteresadoCompleted;
        
        /// <remarks/>
        public event GuardarVendedorCompletedEventHandler GuardarVendedorCompleted;
        
        /// <remarks/>
        public event GetInmueblesParaInteresadoCompletedEventHandler GetInmueblesParaInteresadoCompleted;
        
        /// <remarks/>
        public event BuscarInmueblesCompletedEventHandler BuscarInmueblesCompleted;
        
        /// <remarks/>
        public event GetVendedoresCompletedEventHandler GetVendedoresCompleted;
        
        /// <remarks/>
        public event GetInteresadosCompletedEventHandler GetInteresadosCompleted;
        
        /// <remarks/>
        public event GetInmueblesCompletedEventHandler GetInmueblesCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetFotosDelInmuebleCompletedEventHandler GetFotosDelInmuebleCompleted;
        
        /// <remarks/>
        public event GuardarFotoCompletedEventHandler GuardarFotoCompleted;
        
        /// <remarks/>
        public event TestNotificarSobreInmuebleCompletedEventHandler TestNotificarSobreInmuebleCompleted;
        
        /// <remarks/>
        public event NotificarSobreInmuebleCompletedEventHandler NotificarSobreInmuebleCompleted;
        
        /// <remarks/>
        public event TestNotificarSobreInteresadoCompletedEventHandler TestNotificarSobreInteresadoCompleted;
        
        /// <remarks/>
        public event NotificarSobreInteresadoCompletedEventHandler NotificarSobreInteresadoCompleted;
        
        /// <remarks/>
        public event EliminarVendedorCompletedEventHandler EliminarVendedorCompleted;
        
        /// <remarks/>
        public event EliminarInmuebleCompletedEventHandler EliminarInmuebleCompleted;
        
        /// <remarks/>
        public event EliminarInteresadoCompletedEventHandler EliminarInteresadoCompleted;
        
        /// <remarks/>
        public event GetInmueblesWebCompletedEventHandler GetInmueblesWebCompleted;
        
        /// <remarks/>
        public event GetDolarCompletedEventHandler GetDolarCompleted;
        
        /// <remarks/>
        public event SetDolarCompletedEventHandler SetDolarCompleted;
        
        /// <remarks/>
        public event SubirInmuebleWebCompletedEventHandler SubirInmuebleWebCompleted;
        
        /// <remarks/>
        public event Test2CompletedEventHandler Test2Completed;
        
        /// <remarks/>
        public event Test3CompletedEventHandler Test3Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor, eAmbientes ambientes, eCochera cochera, eUbicacion ubicacion, eEstado estado, eLocalidad localidad) {
            this.Invoke("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda,
                        vendedor,
                        ambientes,
                        cochera,
                        ubicacion,
                        estado,
                        localidad});
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor, eAmbientes ambientes, eCochera cochera, eUbicacion ubicacion, eEstado estado, eLocalidad localidad) {
            this.TestAsync(inmueble, interesado, tipoInmueble, tipoOperacion, moneda, vendedor, ambientes, cochera, ubicacion, estado, localidad, null);
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor, eAmbientes ambientes, eCochera cochera, eUbicacion ubicacion, eEstado estado, eLocalidad localidad, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda,
                        vendedor,
                        ambientes,
                        cochera,
                        ubicacion,
                        estado,
                        localidad}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GuardarInmueble(Inmueble inmueble) {
            object[] results = this.Invoke("GuardarInmueble", new object[] {
                        inmueble});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarInmuebleAsync(Inmueble inmueble) {
            this.GuardarInmuebleAsync(inmueble, null);
        }
        
        /// <remarks/>
        public void GuardarInmuebleAsync(Inmueble inmueble, object userState) {
            if ((this.GuardarInmuebleOperationCompleted == null)) {
                this.GuardarInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInmuebleOperationCompleted);
            }
            this.InvokeAsync("GuardarInmueble", new object[] {
                        inmueble}, this.GuardarInmuebleOperationCompleted, userState);
        }
        
        private void OnGuardarInmuebleOperationCompleted(object arg) {
            if ((this.GuardarInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInmuebleCompleted(this, new GuardarInmuebleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarInteresado(Interesado interesado) {
            this.Invoke("GuardarInteresado", new object[] {
                        interesado});
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado) {
            this.GuardarInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado, object userState) {
            if ((this.GuardarInteresadoOperationCompleted == null)) {
                this.GuardarInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInteresadoOperationCompleted);
            }
            this.InvokeAsync("GuardarInteresado", new object[] {
                        interesado}, this.GuardarInteresadoOperationCompleted, userState);
        }
        
        private void OnGuardarInteresadoOperationCompleted(object arg) {
            if ((this.GuardarInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarVendedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarVendedor(Vendedor vendedor) {
            this.Invoke("GuardarVendedor", new object[] {
                        vendedor});
        }
        
        /// <remarks/>
        public void GuardarVendedorAsync(Vendedor vendedor) {
            this.GuardarVendedorAsync(vendedor, null);
        }
        
        /// <remarks/>
        public void GuardarVendedorAsync(Vendedor vendedor, object userState) {
            if ((this.GuardarVendedorOperationCompleted == null)) {
                this.GuardarVendedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarVendedorOperationCompleted);
            }
            this.InvokeAsync("GuardarVendedor", new object[] {
                        vendedor}, this.GuardarVendedorOperationCompleted, userState);
        }
        
        private void OnGuardarVendedorOperationCompleted(object arg) {
            if ((this.GuardarVendedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarVendedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmueblesParaInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] GetInmueblesParaInteresado(Interesado interesado, decimal cotizacion) {
            object[] results = this.Invoke("GetInmueblesParaInteresado", new object[] {
                        interesado,
                        cotizacion});
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado, decimal cotizacion) {
            this.GetInmueblesParaInteresadoAsync(interesado, cotizacion, null);
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado, decimal cotizacion, object userState) {
            if ((this.GetInmueblesParaInteresadoOperationCompleted == null)) {
                this.GetInmueblesParaInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesParaInteresadoOperationCompleted);
            }
            this.InvokeAsync("GetInmueblesParaInteresado", new object[] {
                        interesado,
                        cotizacion}, this.GetInmueblesParaInteresadoOperationCompleted, userState);
        }
        
        private void OnGetInmueblesParaInteresadoOperationCompleted(object arg) {
            if ((this.GetInmueblesParaInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesParaInteresadoCompleted(this, new GetInmueblesParaInteresadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarInmuebles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] BuscarInmuebles(Inmueble inmueble, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> precioDesde, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> precioHasta) {
            object[] results = this.Invoke("BuscarInmuebles", new object[] {
                        inmueble,
                        precioDesde,
                        precioHasta});
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarInmueblesAsync(Inmueble inmueble, System.Nullable<decimal> precioDesde, System.Nullable<decimal> precioHasta) {
            this.BuscarInmueblesAsync(inmueble, precioDesde, precioHasta, null);
        }
        
        /// <remarks/>
        public void BuscarInmueblesAsync(Inmueble inmueble, System.Nullable<decimal> precioDesde, System.Nullable<decimal> precioHasta, object userState) {
            if ((this.BuscarInmueblesOperationCompleted == null)) {
                this.BuscarInmueblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarInmueblesOperationCompleted);
            }
            this.InvokeAsync("BuscarInmuebles", new object[] {
                        inmueble,
                        precioDesde,
                        precioHasta}, this.BuscarInmueblesOperationCompleted, userState);
        }
        
        private void OnBuscarInmueblesOperationCompleted(object arg) {
            if ((this.BuscarInmueblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarInmueblesCompleted(this, new BuscarInmueblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVendedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vendedor[] GetVendedores() {
            object[] results = this.Invoke("GetVendedores", new object[0]);
            return ((Vendedor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVendedoresAsync() {
            this.GetVendedoresAsync(null);
        }
        
        /// <remarks/>
        public void GetVendedoresAsync(object userState) {
            if ((this.GetVendedoresOperationCompleted == null)) {
                this.GetVendedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVendedoresOperationCompleted);
            }
            this.InvokeAsync("GetVendedores", new object[0], this.GetVendedoresOperationCompleted, userState);
        }
        
        private void OnGetVendedoresOperationCompleted(object arg) {
            if ((this.GetVendedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVendedoresCompleted(this, new GetVendedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInteresados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interesado[] GetInteresados() {
            object[] results = this.Invoke("GetInteresados", new object[0]);
            return ((Interesado[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInteresadosAsync() {
            this.GetInteresadosAsync(null);
        }
        
        /// <remarks/>
        public void GetInteresadosAsync(object userState) {
            if ((this.GetInteresadosOperationCompleted == null)) {
                this.GetInteresadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInteresadosOperationCompleted);
            }
            this.InvokeAsync("GetInteresados", new object[0], this.GetInteresadosOperationCompleted, userState);
        }
        
        private void OnGetInteresadosOperationCompleted(object arg) {
            if ((this.GetInteresadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInteresadosCompleted(this, new GetInteresadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmuebles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] GetInmuebles() {
            object[] results = this.Invoke("GetInmuebles", new object[0]);
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInmueblesAsync() {
            this.GetInmueblesAsync(null);
        }
        
        /// <remarks/>
        public void GetInmueblesAsync(object userState) {
            if ((this.GetInmueblesOperationCompleted == null)) {
                this.GetInmueblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesOperationCompleted);
            }
            this.InvokeAsync("GetInmuebles", new object[0], this.GetInmueblesOperationCompleted, userState);
        }
        
        private void OnGetInmueblesOperationCompleted(object arg) {
            if ((this.GetInmueblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesCompleted(this, new GetInmueblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vendedor Login(string email, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        email,
                        password});
            return ((Vendedor)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        email,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFotosDelInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Foto[] GetFotosDelInmueble(int inmuebleId) {
            object[] results = this.Invoke("GetFotosDelInmueble", new object[] {
                        inmuebleId});
            return ((Foto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFotosDelInmuebleAsync(int inmuebleId) {
            this.GetFotosDelInmuebleAsync(inmuebleId, null);
        }
        
        /// <remarks/>
        public void GetFotosDelInmuebleAsync(int inmuebleId, object userState) {
            if ((this.GetFotosDelInmuebleOperationCompleted == null)) {
                this.GetFotosDelInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFotosDelInmuebleOperationCompleted);
            }
            this.InvokeAsync("GetFotosDelInmueble", new object[] {
                        inmuebleId}, this.GetFotosDelInmuebleOperationCompleted, userState);
        }
        
        private void OnGetFotosDelInmuebleOperationCompleted(object arg) {
            if ((this.GetFotosDelInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFotosDelInmuebleCompleted(this, new GetFotosDelInmuebleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarFoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarFoto(Foto foto) {
            object[] results = this.Invoke("GuardarFoto", new object[] {
                        foto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarFotoAsync(Foto foto) {
            this.GuardarFotoAsync(foto, null);
        }
        
        /// <remarks/>
        public void GuardarFotoAsync(Foto foto, object userState) {
            if ((this.GuardarFotoOperationCompleted == null)) {
                this.GuardarFotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarFotoOperationCompleted);
            }
            this.InvokeAsync("GuardarFoto", new object[] {
                        foto}, this.GuardarFotoOperationCompleted, userState);
        }
        
        private void OnGuardarFotoOperationCompleted(object arg) {
            if ((this.GuardarFotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarFotoCompleted(this, new GuardarFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestNotificarSobreInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestNotificarSobreInmueble() {
            this.Invoke("TestNotificarSobreInmueble", new object[0]);
        }
        
        /// <remarks/>
        public void TestNotificarSobreInmuebleAsync() {
            this.TestNotificarSobreInmuebleAsync(null);
        }
        
        /// <remarks/>
        public void TestNotificarSobreInmuebleAsync(object userState) {
            if ((this.TestNotificarSobreInmuebleOperationCompleted == null)) {
                this.TestNotificarSobreInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestNotificarSobreInmuebleOperationCompleted);
            }
            this.InvokeAsync("TestNotificarSobreInmueble", new object[0], this.TestNotificarSobreInmuebleOperationCompleted, userState);
        }
        
        private void OnTestNotificarSobreInmuebleOperationCompleted(object arg) {
            if ((this.TestNotificarSobreInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestNotificarSobreInmuebleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificarSobreInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotificarSobreInmueble(Interesado interesado, decimal cotizacion) {
            this.Invoke("NotificarSobreInmueble", new object[] {
                        interesado,
                        cotizacion});
        }
        
        /// <remarks/>
        public void NotificarSobreInmuebleAsync(Interesado interesado, decimal cotizacion) {
            this.NotificarSobreInmuebleAsync(interesado, cotizacion, null);
        }
        
        /// <remarks/>
        public void NotificarSobreInmuebleAsync(Interesado interesado, decimal cotizacion, object userState) {
            if ((this.NotificarSobreInmuebleOperationCompleted == null)) {
                this.NotificarSobreInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificarSobreInmuebleOperationCompleted);
            }
            this.InvokeAsync("NotificarSobreInmueble", new object[] {
                        interesado,
                        cotizacion}, this.NotificarSobreInmuebleOperationCompleted, userState);
        }
        
        private void OnNotificarSobreInmuebleOperationCompleted(object arg) {
            if ((this.NotificarSobreInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificarSobreInmuebleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestNotificarSobreInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestNotificarSobreInteresado() {
            this.Invoke("TestNotificarSobreInteresado", new object[0]);
        }
        
        /// <remarks/>
        public void TestNotificarSobreInteresadoAsync() {
            this.TestNotificarSobreInteresadoAsync(null);
        }
        
        /// <remarks/>
        public void TestNotificarSobreInteresadoAsync(object userState) {
            if ((this.TestNotificarSobreInteresadoOperationCompleted == null)) {
                this.TestNotificarSobreInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestNotificarSobreInteresadoOperationCompleted);
            }
            this.InvokeAsync("TestNotificarSobreInteresado", new object[0], this.TestNotificarSobreInteresadoOperationCompleted, userState);
        }
        
        private void OnTestNotificarSobreInteresadoOperationCompleted(object arg) {
            if ((this.TestNotificarSobreInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestNotificarSobreInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificarSobreInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotificarSobreInteresado(Inmueble inmueble, decimal cotizacion) {
            this.Invoke("NotificarSobreInteresado", new object[] {
                        inmueble,
                        cotizacion});
        }
        
        /// <remarks/>
        public void NotificarSobreInteresadoAsync(Inmueble inmueble, decimal cotizacion) {
            this.NotificarSobreInteresadoAsync(inmueble, cotizacion, null);
        }
        
        /// <remarks/>
        public void NotificarSobreInteresadoAsync(Inmueble inmueble, decimal cotizacion, object userState) {
            if ((this.NotificarSobreInteresadoOperationCompleted == null)) {
                this.NotificarSobreInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificarSobreInteresadoOperationCompleted);
            }
            this.InvokeAsync("NotificarSobreInteresado", new object[] {
                        inmueble,
                        cotizacion}, this.NotificarSobreInteresadoOperationCompleted, userState);
        }
        
        private void OnNotificarSobreInteresadoOperationCompleted(object arg) {
            if ((this.NotificarSobreInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificarSobreInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarVendedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarVendedor(Vendedor vendedor) {
            object[] results = this.Invoke("EliminarVendedor", new object[] {
                        vendedor});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarVendedorAsync(Vendedor vendedor) {
            this.EliminarVendedorAsync(vendedor, null);
        }
        
        /// <remarks/>
        public void EliminarVendedorAsync(Vendedor vendedor, object userState) {
            if ((this.EliminarVendedorOperationCompleted == null)) {
                this.EliminarVendedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarVendedorOperationCompleted);
            }
            this.InvokeAsync("EliminarVendedor", new object[] {
                        vendedor}, this.EliminarVendedorOperationCompleted, userState);
        }
        
        private void OnEliminarVendedorOperationCompleted(object arg) {
            if ((this.EliminarVendedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarVendedorCompleted(this, new EliminarVendedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarInmueble(Inmueble inmueble) {
            object[] results = this.Invoke("EliminarInmueble", new object[] {
                        inmueble});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarInmuebleAsync(Inmueble inmueble) {
            this.EliminarInmuebleAsync(inmueble, null);
        }
        
        /// <remarks/>
        public void EliminarInmuebleAsync(Inmueble inmueble, object userState) {
            if ((this.EliminarInmuebleOperationCompleted == null)) {
                this.EliminarInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarInmuebleOperationCompleted);
            }
            this.InvokeAsync("EliminarInmueble", new object[] {
                        inmueble}, this.EliminarInmuebleOperationCompleted, userState);
        }
        
        private void OnEliminarInmuebleOperationCompleted(object arg) {
            if ((this.EliminarInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarInmuebleCompleted(this, new EliminarInmuebleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarInteresado(Interesado interesado) {
            object[] results = this.Invoke("EliminarInteresado", new object[] {
                        interesado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarInteresadoAsync(Interesado interesado) {
            this.EliminarInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void EliminarInteresadoAsync(Interesado interesado, object userState) {
            if ((this.EliminarInteresadoOperationCompleted == null)) {
                this.EliminarInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarInteresadoOperationCompleted);
            }
            this.InvokeAsync("EliminarInteresado", new object[] {
                        interesado}, this.EliminarInteresadoOperationCompleted, userState);
        }
        
        private void OnEliminarInteresadoOperationCompleted(object arg) {
            if ((this.EliminarInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarInteresadoCompleted(this, new EliminarInteresadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmueblesWeb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetInmueblesWeb() {
            this.Invoke("GetInmueblesWeb", new object[0]);
        }
        
        /// <remarks/>
        public void GetInmueblesWebAsync() {
            this.GetInmueblesWebAsync(null);
        }
        
        /// <remarks/>
        public void GetInmueblesWebAsync(object userState) {
            if ((this.GetInmueblesWebOperationCompleted == null)) {
                this.GetInmueblesWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesWebOperationCompleted);
            }
            this.InvokeAsync("GetInmueblesWeb", new object[0], this.GetInmueblesWebOperationCompleted, userState);
        }
        
        private void OnGetInmueblesWebOperationCompleted(object arg) {
            if ((this.GetInmueblesWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesWebCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDolar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetDolar() {
            object[] results = this.Invoke("GetDolar", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetDolarAsync() {
            this.GetDolarAsync(null);
        }
        
        /// <remarks/>
        public void GetDolarAsync(object userState) {
            if ((this.GetDolarOperationCompleted == null)) {
                this.GetDolarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDolarOperationCompleted);
            }
            this.InvokeAsync("GetDolar", new object[0], this.GetDolarOperationCompleted, userState);
        }
        
        private void OnGetDolarOperationCompleted(object arg) {
            if ((this.GetDolarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDolarCompleted(this, new GetDolarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDolar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetDolar(decimal dolar) {
            this.Invoke("SetDolar", new object[] {
                        dolar});
        }
        
        /// <remarks/>
        public void SetDolarAsync(decimal dolar) {
            this.SetDolarAsync(dolar, null);
        }
        
        /// <remarks/>
        public void SetDolarAsync(decimal dolar, object userState) {
            if ((this.SetDolarOperationCompleted == null)) {
                this.SetDolarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDolarOperationCompleted);
            }
            this.InvokeAsync("SetDolar", new object[] {
                        dolar}, this.SetDolarOperationCompleted, userState);
        }
        
        private void OnSetDolarOperationCompleted(object arg) {
            if ((this.SetDolarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDolarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubirInmuebleWeb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SubirInmuebleWeb(int inmuebleId) {
            object[] results = this.Invoke("SubirInmuebleWeb", new object[] {
                        inmuebleId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SubirInmuebleWebAsync(int inmuebleId) {
            this.SubirInmuebleWebAsync(inmuebleId, null);
        }
        
        /// <remarks/>
        public void SubirInmuebleWebAsync(int inmuebleId, object userState) {
            if ((this.SubirInmuebleWebOperationCompleted == null)) {
                this.SubirInmuebleWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubirInmuebleWebOperationCompleted);
            }
            this.InvokeAsync("SubirInmuebleWeb", new object[] {
                        inmuebleId}, this.SubirInmuebleWebOperationCompleted, userState);
        }
        
        private void OnSubirInmuebleWebOperationCompleted(object arg) {
            if ((this.SubirInmuebleWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubirInmuebleWebCompleted(this, new SubirInmuebleWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test2() {
            this.Invoke("Test2", new object[0]);
        }
        
        /// <remarks/>
        public void Test2Async() {
            this.Test2Async(null);
        }
        
        /// <remarks/>
        public void Test2Async(object userState) {
            if ((this.Test2OperationCompleted == null)) {
                this.Test2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTest2OperationCompleted);
            }
            this.InvokeAsync("Test2", new object[0], this.Test2OperationCompleted, userState);
        }
        
        private void OnTest2OperationCompleted(object arg) {
            if ((this.Test2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Test2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test3(int interesadoId) {
            this.Invoke("Test3", new object[] {
                        interesadoId});
        }
        
        /// <remarks/>
        public void Test3Async(int interesadoId) {
            this.Test3Async(interesadoId, null);
        }
        
        /// <remarks/>
        public void Test3Async(int interesadoId, object userState) {
            if ((this.Test3OperationCompleted == null)) {
                this.Test3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTest3OperationCompleted);
            }
            this.InvokeAsync("Test3", new object[] {
                        interesadoId}, this.Test3OperationCompleted, userState);
        }
        
        private void OnTest3OperationCompleted(object arg) {
            if ((this.Test3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Test3Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Inmueble {
        
        private int idField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int operacionField;
        
        private int tipoField;
        
        private int ambientesField;
        
        private bool cocheraField;
        
        private string ubicacionField;
        
        private string antiguedadField;
        
        private string comentariosField;
        
        private string localidadField;
        
        private string calleField;
        
        private string numeroField;
        
        private string pisoField;
        
        private string departamentoField;
        
        private string entreCallesField;
        
        private string metros2TerrenoField;
        
        private string supCubiertaField;
        
        private int monedaField;
        
        private System.Nullable<decimal> precioField;
        
        private string observacionesField;
        
        private int cargadoPorField;
        
        private string contactoField;
        
        private string referenciaField;
        
        private bool disponibleField;
        
        private int estadoField;
        
        private int webIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int Operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int Ambientes {
            get {
                return this.ambientesField;
            }
            set {
                this.ambientesField = value;
            }
        }
        
        /// <remarks/>
        public bool Cochera {
            get {
                return this.cocheraField;
            }
            set {
                this.cocheraField = value;
            }
        }
        
        /// <remarks/>
        public string Ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        public string Antiguedad {
            get {
                return this.antiguedadField;
            }
            set {
                this.antiguedadField = value;
            }
        }
        
        /// <remarks/>
        public string Comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string EntreCalles {
            get {
                return this.entreCallesField;
            }
            set {
                this.entreCallesField = value;
            }
        }
        
        /// <remarks/>
        public string Metros2Terreno {
            get {
                return this.metros2TerrenoField;
            }
            set {
                this.metros2TerrenoField = value;
            }
        }
        
        /// <remarks/>
        public string SupCubierta {
            get {
                return this.supCubiertaField;
            }
            set {
                this.supCubiertaField = value;
            }
        }
        
        /// <remarks/>
        public int Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public int CargadoPor {
            get {
                return this.cargadoPorField;
            }
            set {
                this.cargadoPorField = value;
            }
        }
        
        /// <remarks/>
        public string Contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public bool Disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public int WebId {
            get {
                return this.webIdField;
            }
            set {
                this.webIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Foto {
        
        private int idField;
        
        private int inmuebleIdField;
        
        private byte[] imagenField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int InmuebleId {
            get {
                return this.inmuebleIdField;
            }
            set {
                this.inmuebleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vendedor {
        
        private int idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string celularField;
        
        private string legajoField;
        
        private string emailField;
        
        private string dNIField;
        
        private string passwordField;
        
        private string fullNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Legajo {
            get {
                return this.legajoField;
            }
            set {
                this.legajoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Interesado {
        
        private int idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string emailField;
        
        private System.Nullable<decimal> montoDesdeField;
        
        private System.Nullable<decimal> montoHastaField;
        
        private int tipoDeMonedaField;
        
        private int tipoDeOperacionField;
        
        private int tipoDeInmuebleField;
        
        private string observacionesField;
        
        private bool disponibleField;
        
        private int ambientesField;
        
        private string localidadField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoDesde {
            get {
                return this.montoDesdeField;
            }
            set {
                this.montoDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoHasta {
            get {
                return this.montoHastaField;
            }
            set {
                this.montoHastaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeMoneda {
            get {
                return this.tipoDeMonedaField;
            }
            set {
                this.tipoDeMonedaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeOperacion {
            get {
                return this.tipoDeOperacionField;
            }
            set {
                this.tipoDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeInmueble {
            get {
                return this.tipoDeInmuebleField;
            }
            set {
                this.tipoDeInmuebleField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public bool Disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        public int Ambientes {
            get {
                return this.ambientesField;
            }
            set {
                this.ambientesField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoInmueble {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Terreno,
        
        /// <remarks/>
        Departamento,
        
        /// <remarks/>
        Casa,
        
        /// <remarks/>
        Quinta,
        
        /// <remarks/>
        Local,
        
        /// <remarks/>
        FondoDeComercio,
        
        /// <remarks/>
        Oficina,
        
        /// <remarks/>
        Galpon,
        
        /// <remarks/>
        Pozo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoOperacion {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Venta,
        
        /// <remarks/>
        Alquiler,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eMoneda {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Peso,
        
        /// <remarks/>
        Dolar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eAmbientes {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Monoambiente,
        
        /// <remarks/>
        Dos_Ambiente,
        
        /// <remarks/>
        Tres_Ambientes,
        
        /// <remarks/>
        Cuatro_Ambientes,
        
        /// <remarks/>
        Cinco_O_Mas_Ambientes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eCochera {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Si,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eUbicacion {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Frente,
        
        /// <remarks/>
        Contrafrente,
        
        /// <remarks/>
        Lateral,
        
        /// <remarks/>
        Interno,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eEstado {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Exelente,
        
        /// <remarks/>
        Muy_Bueno,
        
        /// <remarks/>
        Bueno,
        
        /// <remarks/>
        Regular,
        
        /// <remarks/>
        En_Construccion,
        
        /// <remarks/>
        En_Pozo,
        
        /// <remarks/>
        A_Estrenar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eLocalidad {
        
        /// <remarks/>
        Sin_Especificar,
        
        /// <remarks/>
        Santa_Rosa,
        
        /// <remarks/>
        Toay,
        
        /// <remarks/>
        Buenos_Aires,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarInmuebleCompletedEventHandler(object sender, GuardarInmuebleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarInmuebleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarInmuebleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarVendedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesParaInteresadoCompletedEventHandler(object sender, GetInmueblesParaInteresadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInmueblesParaInteresadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInmueblesParaInteresadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BuscarInmueblesCompletedEventHandler(object sender, BuscarInmueblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarInmueblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarInmueblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetVendedoresCompletedEventHandler(object sender, GetVendedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVendedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVendedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vendedor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vendedor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInteresadosCompletedEventHandler(object sender, GetInteresadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInteresadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInteresadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interesado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interesado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesCompletedEventHandler(object sender, GetInmueblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInmueblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInmueblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vendedor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vendedor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFotosDelInmuebleCompletedEventHandler(object sender, GetFotosDelInmuebleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFotosDelInmuebleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFotosDelInmuebleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Foto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Foto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarFotoCompletedEventHandler(object sender, GuardarFotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarFotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarFotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestNotificarSobreInmuebleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NotificarSobreInmuebleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestNotificarSobreInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NotificarSobreInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EliminarVendedorCompletedEventHandler(object sender, EliminarVendedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarVendedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarVendedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EliminarInmuebleCompletedEventHandler(object sender, EliminarInmuebleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarInmuebleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarInmuebleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EliminarInteresadoCompletedEventHandler(object sender, EliminarInteresadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarInteresadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarInteresadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesWebCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDolarCompletedEventHandler(object sender, GetDolarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDolarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDolarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetDolarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SubirInmuebleWebCompletedEventHandler(object sender, SubirInmuebleWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubirInmuebleWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubirInmuebleWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Test2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Test3CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591