//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InmobiliariaForms.InmobiliariaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarVendedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesParaInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarInmueblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVendedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInteresadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFotosDelInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarFotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificarSobreInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificarSobreInteresadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::InmobiliariaForms.Properties.Settings.Default.InmobiliariaForms_InmobiliariaService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event GuardarInmuebleCompletedEventHandler GuardarInmuebleCompleted;
        
        /// <remarks/>
        public event GuardarInteresadoCompletedEventHandler GuardarInteresadoCompleted;
        
        /// <remarks/>
        public event GuardarVendedorCompletedEventHandler GuardarVendedorCompleted;
        
        /// <remarks/>
        public event GetInmueblesParaInteresadoCompletedEventHandler GetInmueblesParaInteresadoCompleted;
        
        /// <remarks/>
        public event BuscarInmueblesCompletedEventHandler BuscarInmueblesCompleted;
        
        /// <remarks/>
        public event GetVendedoresCompletedEventHandler GetVendedoresCompleted;
        
        /// <remarks/>
        public event GetInteresadosCompletedEventHandler GetInteresadosCompleted;
        
        /// <remarks/>
        public event GetInmueblesCompletedEventHandler GetInmueblesCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetFotosDelInmuebleCompletedEventHandler GetFotosDelInmuebleCompleted;
        
        /// <remarks/>
        public event GuardarFotoCompletedEventHandler GuardarFotoCompleted;
        
        /// <remarks/>
        public event NotificarSobreInmuebleCompletedEventHandler NotificarSobreInmuebleCompleted;
        
        /// <remarks/>
        public event NotificarSobreInteresadoCompletedEventHandler NotificarSobreInteresadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor) {
            this.Invoke("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda,
                        vendedor});
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor) {
            this.TestAsync(inmueble, interesado, tipoInmueble, tipoOperacion, moneda, vendedor, null);
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, Vendedor vendedor, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda,
                        vendedor}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarInmueble(Inmueble inmueble) {
            this.Invoke("GuardarInmueble", new object[] {
                        inmueble});
        }
        
        /// <remarks/>
        public void GuardarInmuebleAsync(Inmueble inmueble) {
            this.GuardarInmuebleAsync(inmueble, null);
        }
        
        /// <remarks/>
        public void GuardarInmuebleAsync(Inmueble inmueble, object userState) {
            if ((this.GuardarInmuebleOperationCompleted == null)) {
                this.GuardarInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInmuebleOperationCompleted);
            }
            this.InvokeAsync("GuardarInmueble", new object[] {
                        inmueble}, this.GuardarInmuebleOperationCompleted, userState);
        }
        
        private void OnGuardarInmuebleOperationCompleted(object arg) {
            if ((this.GuardarInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInmuebleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarInteresado(Interesado interesado) {
            this.Invoke("GuardarInteresado", new object[] {
                        interesado});
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado) {
            this.GuardarInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado, object userState) {
            if ((this.GuardarInteresadoOperationCompleted == null)) {
                this.GuardarInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInteresadoOperationCompleted);
            }
            this.InvokeAsync("GuardarInteresado", new object[] {
                        interesado}, this.GuardarInteresadoOperationCompleted, userState);
        }
        
        private void OnGuardarInteresadoOperationCompleted(object arg) {
            if ((this.GuardarInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarVendedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarVendedor(Vendedor vendedor) {
            this.Invoke("GuardarVendedor", new object[] {
                        vendedor});
        }
        
        /// <remarks/>
        public void GuardarVendedorAsync(Vendedor vendedor) {
            this.GuardarVendedorAsync(vendedor, null);
        }
        
        /// <remarks/>
        public void GuardarVendedorAsync(Vendedor vendedor, object userState) {
            if ((this.GuardarVendedorOperationCompleted == null)) {
                this.GuardarVendedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarVendedorOperationCompleted);
            }
            this.InvokeAsync("GuardarVendedor", new object[] {
                        vendedor}, this.GuardarVendedorOperationCompleted, userState);
        }
        
        private void OnGuardarVendedorOperationCompleted(object arg) {
            if ((this.GuardarVendedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarVendedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmueblesParaInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] GetInmueblesParaInteresado(Interesado interesado) {
            object[] results = this.Invoke("GetInmueblesParaInteresado", new object[] {
                        interesado});
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado) {
            this.GetInmueblesParaInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado, object userState) {
            if ((this.GetInmueblesParaInteresadoOperationCompleted == null)) {
                this.GetInmueblesParaInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesParaInteresadoOperationCompleted);
            }
            this.InvokeAsync("GetInmueblesParaInteresado", new object[] {
                        interesado}, this.GetInmueblesParaInteresadoOperationCompleted, userState);
        }
        
        private void OnGetInmueblesParaInteresadoOperationCompleted(object arg) {
            if ((this.GetInmueblesParaInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesParaInteresadoCompleted(this, new GetInmueblesParaInteresadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarInmuebles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] BuscarInmuebles(Inmueble inmueble, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> precioDesde, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> precioHasta) {
            object[] results = this.Invoke("BuscarInmuebles", new object[] {
                        inmueble,
                        precioDesde,
                        precioHasta});
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarInmueblesAsync(Inmueble inmueble, System.Nullable<decimal> precioDesde, System.Nullable<decimal> precioHasta) {
            this.BuscarInmueblesAsync(inmueble, precioDesde, precioHasta, null);
        }
        
        /// <remarks/>
        public void BuscarInmueblesAsync(Inmueble inmueble, System.Nullable<decimal> precioDesde, System.Nullable<decimal> precioHasta, object userState) {
            if ((this.BuscarInmueblesOperationCompleted == null)) {
                this.BuscarInmueblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarInmueblesOperationCompleted);
            }
            this.InvokeAsync("BuscarInmuebles", new object[] {
                        inmueble,
                        precioDesde,
                        precioHasta}, this.BuscarInmueblesOperationCompleted, userState);
        }
        
        private void OnBuscarInmueblesOperationCompleted(object arg) {
            if ((this.BuscarInmueblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarInmueblesCompleted(this, new BuscarInmueblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVendedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vendedor[] GetVendedores() {
            object[] results = this.Invoke("GetVendedores", new object[0]);
            return ((Vendedor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVendedoresAsync() {
            this.GetVendedoresAsync(null);
        }
        
        /// <remarks/>
        public void GetVendedoresAsync(object userState) {
            if ((this.GetVendedoresOperationCompleted == null)) {
                this.GetVendedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVendedoresOperationCompleted);
            }
            this.InvokeAsync("GetVendedores", new object[0], this.GetVendedoresOperationCompleted, userState);
        }
        
        private void OnGetVendedoresOperationCompleted(object arg) {
            if ((this.GetVendedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVendedoresCompleted(this, new GetVendedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInteresados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interesado[] GetInteresados() {
            object[] results = this.Invoke("GetInteresados", new object[0]);
            return ((Interesado[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInteresadosAsync() {
            this.GetInteresadosAsync(null);
        }
        
        /// <remarks/>
        public void GetInteresadosAsync(object userState) {
            if ((this.GetInteresadosOperationCompleted == null)) {
                this.GetInteresadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInteresadosOperationCompleted);
            }
            this.InvokeAsync("GetInteresados", new object[0], this.GetInteresadosOperationCompleted, userState);
        }
        
        private void OnGetInteresadosOperationCompleted(object arg) {
            if ((this.GetInteresadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInteresadosCompleted(this, new GetInteresadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmuebles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] GetInmuebles() {
            object[] results = this.Invoke("GetInmuebles", new object[0]);
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInmueblesAsync() {
            this.GetInmueblesAsync(null);
        }
        
        /// <remarks/>
        public void GetInmueblesAsync(object userState) {
            if ((this.GetInmueblesOperationCompleted == null)) {
                this.GetInmueblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesOperationCompleted);
            }
            this.InvokeAsync("GetInmuebles", new object[0], this.GetInmueblesOperationCompleted, userState);
        }
        
        private void OnGetInmueblesOperationCompleted(object arg) {
            if ((this.GetInmueblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesCompleted(this, new GetInmueblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vendedor Login(string dni, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        dni,
                        password});
            return ((Vendedor)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string dni, string password) {
            this.LoginAsync(dni, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string dni, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        dni,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFotosDelInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Foto[] GetFotosDelInmueble(int inmuebleId) {
            object[] results = this.Invoke("GetFotosDelInmueble", new object[] {
                        inmuebleId});
            return ((Foto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFotosDelInmuebleAsync(int inmuebleId) {
            this.GetFotosDelInmuebleAsync(inmuebleId, null);
        }
        
        /// <remarks/>
        public void GetFotosDelInmuebleAsync(int inmuebleId, object userState) {
            if ((this.GetFotosDelInmuebleOperationCompleted == null)) {
                this.GetFotosDelInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFotosDelInmuebleOperationCompleted);
            }
            this.InvokeAsync("GetFotosDelInmueble", new object[] {
                        inmuebleId}, this.GetFotosDelInmuebleOperationCompleted, userState);
        }
        
        private void OnGetFotosDelInmuebleOperationCompleted(object arg) {
            if ((this.GetFotosDelInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFotosDelInmuebleCompleted(this, new GetFotosDelInmuebleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarFoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarFoto(Foto foto) {
            object[] results = this.Invoke("GuardarFoto", new object[] {
                        foto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarFotoAsync(Foto foto) {
            this.GuardarFotoAsync(foto, null);
        }
        
        /// <remarks/>
        public void GuardarFotoAsync(Foto foto, object userState) {
            if ((this.GuardarFotoOperationCompleted == null)) {
                this.GuardarFotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarFotoOperationCompleted);
            }
            this.InvokeAsync("GuardarFoto", new object[] {
                        foto}, this.GuardarFotoOperationCompleted, userState);
        }
        
        private void OnGuardarFotoOperationCompleted(object arg) {
            if ((this.GuardarFotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarFotoCompleted(this, new GuardarFotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificarSobreInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotificarSobreInmueble(Interesado interesado) {
            this.Invoke("NotificarSobreInmueble", new object[] {
                        interesado});
        }
        
        /// <remarks/>
        public void NotificarSobreInmuebleAsync(Interesado interesado) {
            this.NotificarSobreInmuebleAsync(interesado, null);
        }
        
        /// <remarks/>
        public void NotificarSobreInmuebleAsync(Interesado interesado, object userState) {
            if ((this.NotificarSobreInmuebleOperationCompleted == null)) {
                this.NotificarSobreInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificarSobreInmuebleOperationCompleted);
            }
            this.InvokeAsync("NotificarSobreInmueble", new object[] {
                        interesado}, this.NotificarSobreInmuebleOperationCompleted, userState);
        }
        
        private void OnNotificarSobreInmuebleOperationCompleted(object arg) {
            if ((this.NotificarSobreInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificarSobreInmuebleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificarSobreInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotificarSobreInteresado(Inmueble inmueble) {
            this.Invoke("NotificarSobreInteresado", new object[] {
                        inmueble});
        }
        
        /// <remarks/>
        public void NotificarSobreInteresadoAsync(Inmueble inmueble) {
            this.NotificarSobreInteresadoAsync(inmueble, null);
        }
        
        /// <remarks/>
        public void NotificarSobreInteresadoAsync(Inmueble inmueble, object userState) {
            if ((this.NotificarSobreInteresadoOperationCompleted == null)) {
                this.NotificarSobreInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificarSobreInteresadoOperationCompleted);
            }
            this.InvokeAsync("NotificarSobreInteresado", new object[] {
                        inmueble}, this.NotificarSobreInteresadoOperationCompleted, userState);
        }
        
        private void OnNotificarSobreInteresadoOperationCompleted(object arg) {
            if ((this.NotificarSobreInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificarSobreInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Inmueble {
        
        private int idField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int operacionField;
        
        private int tipoField;
        
        private string localidadField;
        
        private string barrioField;
        
        private string calleField;
        
        private string numeroField;
        
        private string pisoField;
        
        private string departamentoField;
        
        private string entreCallesField;
        
        private string metros2TerrenoField;
        
        private string supCubiertaField;
        
        private int monedaField;
        
        private System.Nullable<decimal> precioField;
        
        private string observacionesField;
        
        private string dormitoriosField;
        
        private string bañosField;
        
        private string comedorField;
        
        private string cocinaField;
        
        private string garageField;
        
        private string patioField;
        
        private string otrasDependenciasField;
        
        private string valorMetro2Field;
        
        private int cargadoPorField;
        
        private string contactoField;
        
        private string referenciaField;
        
        private string otrosField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int Operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        public string Barrio {
            get {
                return this.barrioField;
            }
            set {
                this.barrioField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string EntreCalles {
            get {
                return this.entreCallesField;
            }
            set {
                this.entreCallesField = value;
            }
        }
        
        /// <remarks/>
        public string Metros2Terreno {
            get {
                return this.metros2TerrenoField;
            }
            set {
                this.metros2TerrenoField = value;
            }
        }
        
        /// <remarks/>
        public string SupCubierta {
            get {
                return this.supCubiertaField;
            }
            set {
                this.supCubiertaField = value;
            }
        }
        
        /// <remarks/>
        public int Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string Dormitorios {
            get {
                return this.dormitoriosField;
            }
            set {
                this.dormitoriosField = value;
            }
        }
        
        /// <remarks/>
        public string Baños {
            get {
                return this.bañosField;
            }
            set {
                this.bañosField = value;
            }
        }
        
        /// <remarks/>
        public string Comedor {
            get {
                return this.comedorField;
            }
            set {
                this.comedorField = value;
            }
        }
        
        /// <remarks/>
        public string Cocina {
            get {
                return this.cocinaField;
            }
            set {
                this.cocinaField = value;
            }
        }
        
        /// <remarks/>
        public string Garage {
            get {
                return this.garageField;
            }
            set {
                this.garageField = value;
            }
        }
        
        /// <remarks/>
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
            }
        }
        
        /// <remarks/>
        public string OtrasDependencias {
            get {
                return this.otrasDependenciasField;
            }
            set {
                this.otrasDependenciasField = value;
            }
        }
        
        /// <remarks/>
        public string ValorMetro2 {
            get {
                return this.valorMetro2Field;
            }
            set {
                this.valorMetro2Field = value;
            }
        }
        
        /// <remarks/>
        public int CargadoPor {
            get {
                return this.cargadoPorField;
            }
            set {
                this.cargadoPorField = value;
            }
        }
        
        /// <remarks/>
        public string Contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Otros {
            get {
                return this.otrosField;
            }
            set {
                this.otrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Foto {
        
        private int idField;
        
        private int inmuebleIdField;
        
        private byte[] imagenField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int InmuebleId {
            get {
                return this.inmuebleIdField;
            }
            set {
                this.inmuebleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vendedor {
        
        private int idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string celularField;
        
        private string legajoField;
        
        private string emailField;
        
        private string dNIField;
        
        private string passwordField;
        
        private string fullNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Legajo {
            get {
                return this.legajoField;
            }
            set {
                this.legajoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Interesado {
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string emailField;
        
        private System.Nullable<decimal> montoDesdeField;
        
        private System.Nullable<decimal> montoHastaField;
        
        private int tipoDeMonedaField;
        
        private int tipoDeOperacionField;
        
        private int tipoDeInmuebleField;
        
        private string dormitoriosField;
        
        private bool paraInversionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoDesde {
            get {
                return this.montoDesdeField;
            }
            set {
                this.montoDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoHasta {
            get {
                return this.montoHastaField;
            }
            set {
                this.montoHastaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeMoneda {
            get {
                return this.tipoDeMonedaField;
            }
            set {
                this.tipoDeMonedaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeOperacion {
            get {
                return this.tipoDeOperacionField;
            }
            set {
                this.tipoDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeInmueble {
            get {
                return this.tipoDeInmuebleField;
            }
            set {
                this.tipoDeInmuebleField = value;
            }
        }
        
        /// <remarks/>
        public string Dormitorios {
            get {
                return this.dormitoriosField;
            }
            set {
                this.dormitoriosField = value;
            }
        }
        
        /// <remarks/>
        public bool ParaInversion {
            get {
                return this.paraInversionField;
            }
            set {
                this.paraInversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoInmueble {
        
        /// <remarks/>
        Casa,
        
        /// <remarks/>
        Terreno,
        
        /// <remarks/>
        Departamento,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoOperacion {
        
        /// <remarks/>
        Venta,
        
        /// <remarks/>
        Alquiler,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eMoneda {
        
        /// <remarks/>
        Peso,
        
        /// <remarks/>
        Dolar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarInmuebleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarVendedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesParaInteresadoCompletedEventHandler(object sender, GetInmueblesParaInteresadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInmueblesParaInteresadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInmueblesParaInteresadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BuscarInmueblesCompletedEventHandler(object sender, BuscarInmueblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarInmueblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarInmueblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetVendedoresCompletedEventHandler(object sender, GetVendedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVendedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVendedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vendedor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vendedor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInteresadosCompletedEventHandler(object sender, GetInteresadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInteresadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInteresadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interesado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interesado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesCompletedEventHandler(object sender, GetInmueblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInmueblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInmueblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vendedor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vendedor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFotosDelInmuebleCompletedEventHandler(object sender, GetFotosDelInmuebleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFotosDelInmuebleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFotosDelInmuebleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Foto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Foto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarFotoCompletedEventHandler(object sender, GuardarFotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarFotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarFotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NotificarSobreInmuebleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NotificarSobreInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591