//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InmobiliariaForms.InmobiliariaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearInmuebleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInteresadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInmueblesParaInteresadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::InmobiliariaForms.Properties.Settings.Default.InmobiliariaForms_InmobiliariaService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event CrearInmuebleCompletedEventHandler CrearInmuebleCompleted;
        
        /// <remarks/>
        public event GuardarInteresadoCompletedEventHandler GuardarInteresadoCompleted;
        
        /// <remarks/>
        public event GetInmueblesParaInteresadoCompletedEventHandler GetInmueblesParaInteresadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Test(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda) {
            this.Invoke("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda});
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda) {
            this.TestAsync(inmueble, interesado, tipoInmueble, tipoOperacion, moneda, null);
        }
        
        /// <remarks/>
        public void TestAsync(Inmueble inmueble, Interesado interesado, eTipoInmueble tipoInmueble, eTipoOperacion tipoOperacion, eMoneda moneda, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        inmueble,
                        interesado,
                        tipoInmueble,
                        tipoOperacion,
                        moneda}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearInmueble", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearInmueble(Inmueble inmueble) {
            this.Invoke("CrearInmueble", new object[] {
                        inmueble});
        }
        
        /// <remarks/>
        public void CrearInmuebleAsync(Inmueble inmueble) {
            this.CrearInmuebleAsync(inmueble, null);
        }
        
        /// <remarks/>
        public void CrearInmuebleAsync(Inmueble inmueble, object userState) {
            if ((this.CrearInmuebleOperationCompleted == null)) {
                this.CrearInmuebleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearInmuebleOperationCompleted);
            }
            this.InvokeAsync("CrearInmueble", new object[] {
                        inmueble}, this.CrearInmuebleOperationCompleted, userState);
        }
        
        private void OnCrearInmuebleOperationCompleted(object arg) {
            if ((this.CrearInmuebleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearInmuebleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarInteresado(Interesado interesado) {
            this.Invoke("GuardarInteresado", new object[] {
                        interesado});
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado) {
            this.GuardarInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void GuardarInteresadoAsync(Interesado interesado, object userState) {
            if ((this.GuardarInteresadoOperationCompleted == null)) {
                this.GuardarInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInteresadoOperationCompleted);
            }
            this.InvokeAsync("GuardarInteresado", new object[] {
                        interesado}, this.GuardarInteresadoOperationCompleted, userState);
        }
        
        private void OnGuardarInteresadoOperationCompleted(object arg) {
            if ((this.GuardarInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInteresadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInmueblesParaInteresado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Inmueble[] GetInmueblesParaInteresado(Interesado interesado) {
            object[] results = this.Invoke("GetInmueblesParaInteresado", new object[] {
                        interesado});
            return ((Inmueble[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado) {
            this.GetInmueblesParaInteresadoAsync(interesado, null);
        }
        
        /// <remarks/>
        public void GetInmueblesParaInteresadoAsync(Interesado interesado, object userState) {
            if ((this.GetInmueblesParaInteresadoOperationCompleted == null)) {
                this.GetInmueblesParaInteresadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInmueblesParaInteresadoOperationCompleted);
            }
            this.InvokeAsync("GetInmueblesParaInteresado", new object[] {
                        interesado}, this.GetInmueblesParaInteresadoOperationCompleted, userState);
        }
        
        private void OnGetInmueblesParaInteresadoOperationCompleted(object arg) {
            if ((this.GetInmueblesParaInteresadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInmueblesParaInteresadoCompleted(this, new GetInmueblesParaInteresadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Inmueble {
        
        private int idField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int operacionField;
        
        private int tipoField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string localidadField;
        
        private string barrioField;
        
        private string calleField;
        
        private System.Nullable<int> numeroField;
        
        private System.Nullable<int> pisoField;
        
        private string departamentoField;
        
        private string entreCallesField;
        
        private string metros2TerrenoField;
        
        private int supCubiertaField;
        
        private int monedaField;
        
        private System.Nullable<decimal> precioField;
        
        private string observacionesField;
        
        private System.Nullable<int> dormitoriosField;
        
        private string bañosField;
        
        private string comedorField;
        
        private string cocinaField;
        
        private string garageField;
        
        private string patioField;
        
        private string otrasDependenciasField;
        
        private System.Nullable<decimal> valorMetro2Field;
        
        private string cargadoPorField;
        
        private string contactoField;
        
        private string referenciaField;
        
        private string otroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int Operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <remarks/>
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        public string Barrio {
            get {
                return this.barrioField;
            }
            set {
                this.barrioField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string EntreCalles {
            get {
                return this.entreCallesField;
            }
            set {
                this.entreCallesField = value;
            }
        }
        
        /// <remarks/>
        public string Metros2Terreno {
            get {
                return this.metros2TerrenoField;
            }
            set {
                this.metros2TerrenoField = value;
            }
        }
        
        /// <remarks/>
        public int SupCubierta {
            get {
                return this.supCubiertaField;
            }
            set {
                this.supCubiertaField = value;
            }
        }
        
        /// <remarks/>
        public int Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Dormitorios {
            get {
                return this.dormitoriosField;
            }
            set {
                this.dormitoriosField = value;
            }
        }
        
        /// <remarks/>
        public string Baños {
            get {
                return this.bañosField;
            }
            set {
                this.bañosField = value;
            }
        }
        
        /// <remarks/>
        public string Comedor {
            get {
                return this.comedorField;
            }
            set {
                this.comedorField = value;
            }
        }
        
        /// <remarks/>
        public string Cocina {
            get {
                return this.cocinaField;
            }
            set {
                this.cocinaField = value;
            }
        }
        
        /// <remarks/>
        public string Garage {
            get {
                return this.garageField;
            }
            set {
                this.garageField = value;
            }
        }
        
        /// <remarks/>
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
            }
        }
        
        /// <remarks/>
        public string OtrasDependencias {
            get {
                return this.otrasDependenciasField;
            }
            set {
                this.otrasDependenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ValorMetro2 {
            get {
                return this.valorMetro2Field;
            }
            set {
                this.valorMetro2Field = value;
            }
        }
        
        /// <remarks/>
        public string CargadoPor {
            get {
                return this.cargadoPorField;
            }
            set {
                this.cargadoPorField = value;
            }
        }
        
        /// <remarks/>
        public string Contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Otro {
            get {
                return this.otroField;
            }
            set {
                this.otroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Interesado {
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string emailField;
        
        private System.Nullable<decimal> montoDesdeField;
        
        private System.Nullable<decimal> montoHastaField;
        
        private int tipoDeOperacionField;
        
        private int tipoDeInmuebleField;
        
        private System.Nullable<int> dormitoriosField;
        
        private bool paraInversionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoDesde {
            get {
                return this.montoDesdeField;
            }
            set {
                this.montoDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoHasta {
            get {
                return this.montoHastaField;
            }
            set {
                this.montoHastaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeOperacion {
            get {
                return this.tipoDeOperacionField;
            }
            set {
                this.tipoDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        public int TipoDeInmueble {
            get {
                return this.tipoDeInmuebleField;
            }
            set {
                this.tipoDeInmuebleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Dormitorios {
            get {
                return this.dormitoriosField;
            }
            set {
                this.dormitoriosField = value;
            }
        }
        
        /// <remarks/>
        public bool ParaInversion {
            get {
                return this.paraInversionField;
            }
            set {
                this.paraInversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoInmueble {
        
        /// <remarks/>
        Casa,
        
        /// <remarks/>
        Terreno,
        
        /// <remarks/>
        Departamento,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eTipoOperacion {
        
        /// <remarks/>
        Venta,
        
        /// <remarks/>
        Alquiler,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eMoneda {
        
        /// <remarks/>
        Peso,
        
        /// <remarks/>
        Dolar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CrearInmuebleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GuardarInteresadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetInmueblesParaInteresadoCompletedEventHandler(object sender, GetInmueblesParaInteresadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInmueblesParaInteresadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInmueblesParaInteresadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Inmueble[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Inmueble[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591