#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SolucionInmobiliariaAndroid.Resource", IsApplication=true)]

namespace SolucionInmobiliariaAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int my_lightyellow = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int my_yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Inmueble = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Persona = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070020
			public const int btCancelar = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int btGuardar = 2131165217;
			
			// aapt resource value: 0x7f070006
			public const int btLogin = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int btNuevaInteresado = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int btNuevoInmueble = 2131165186;
			
			// aapt resource value: 0x7f070022
			public const int button1 = 2131165218;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout2 = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout4 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout5 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout6 = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout7 = 2131165215;
			
			// aapt resource value: 0x7f070018
			public const int spnAmbientes = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int spnCochera = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int spnEstado = 2131165213;
			
			// aapt resource value: 0x7f070013
			public const int spnMoneda = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int spnOperacion = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int spnTipoInmueble = 2131165192;
			
			// aapt resource value: 0x7f070028
			public const int spnTipoMoneda = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int spnTipoOperacion = 2131165225;
			
			// aapt resource value: 0x7f07001c
			public const int spnUbicacion = 2131165212;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f07001b
			public const int txAntiguedad = 2131165211;
			
			// aapt resource value: 0x7f070024
			public const int txApellido = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int txCalle = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int txDepto = 2131165199;
			
			// aapt resource value: 0x7f070026
			public const int txEmail = 2131165222;
			
			// aapt resource value: 0x7f070010
			public const int txEntreCalles = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int txLocalidad = 2131165194;
			
			// aapt resource value: 0x7f070027
			public const int txMonto = 2131165223;
			
			// aapt resource value: 0x7f070015
			public const int txMtsTerreno = 2131165205;
			
			// aapt resource value: 0x7f070023
			public const int txNombre = 2131165219;
			
			// aapt resource value: 0x7f07000d
			public const int txNumero = 2131165197;
			
			// aapt resource value: 0x7f07001e
			public const int txObservaciones = 2131165214;
			
			// aapt resource value: 0x7f070005
			public const int txPassword = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int txPiso = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int txPrecio = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int txSupCubierta = 2131165206;
			
			// aapt resource value: 0x7f070025
			public const int txTelefono = 2131165221;
			
			// aapt resource value: 0x7f070000
			public const int txUsuario = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NuevoInmueble = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NuevoInteresado = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
